#!/bin/sh

if [ ! -z "$BLOCK_BUTTON" ]; then
	case $BLOCK_BUTTON in
		1) brightness dec 1  ;;
		2) brightnessGUI     ;; # Launches a python script that creates a GUI for adjusting brightness
		3) brightness inc 1  ;;
		5) brightness dec 25 ;;
		4) brightness inc 25 ;;
	esac
fi

max=`brightness info max`
current=`brightness info current`
percentage=$(( current * 100 / max ))

printf " %s/%s[%s%%]\n" $current $max $percentage
