#!/bin/bash

totalMB=`free -m | grep "Mem:" | tr -s ' ' | cut -d ' ' -f 2`
usedMB=`free -m | grep "Mem:" | tr -s ' ' | cut -d ' ' -f 3`
perc=`echo "scale=1; $usedMB * 100 / $totalMB" | bc`

totalGB=`echo "scale=1; $totalMB / 1000" | bc`

if [ $usedMB -lt 1000 ]
then
	echo '<span foreground="red">RAM:'${usedMB}'MB/'${totalGB}'GB['$perc'%]</span>'
else
	usedGB=`echo "scale=2; $usedMB / 1000" | bc`
	echo '<span foreground="red">'${usedGB}'GB/'${totalGB}'GB['$perc'%]</span>'
	
fi

