#!/bin/bash
currentvolume=`pactl list sinks | grep -A 9 "Sink #0"| grep "Volume:" | tr -s ' ' | cut -d ' ' -f 5 | tr -d '%'`

muted=`pactl list sinks | grep -A 8 "Sink #0" | grep "Mute:" | tr -s ' ' | cut -d ' ' -f 2`


if [ "$muted" == "yes" ]
then
	echo "  [MUTED,$currentvolume%]"
else
	if [[ $currentvolume -eq 0 ]]
	then
		echo "  [$currentvolume%]"
	elif [ $currentvolume -gt 0 ] && [ $currentvolume -le 50 ]
	then
		echo "  [$currentvolume%]"
	elif [ $currentvolume -gt 50 ]
	then
		echo "  [$currentvolume%]"
	fi
fi
