command=/usr/libexec/i3blocks/$BLOCK_NAME
separator_block_width=15
markup=pango

[gpu]
command=smi=`nvidia-smi | grep -A 3 Temp | grep "%" | tr -s ' '`; printf "<span foreground='#00FF00'>%s.0°C %s</span>\n" "`echo "$smi" | cut -d ' ' -f 3 | tr -d 'C'`" "`echo "$smi" | cut -d ' ' -f 13`"
interval=2

[cpu]
command=sensors=`sensors | grep -A 3 "Core 0:" | tr -s " "`; printf "<span foreground=\"#4444ff\">%s°C %.1f%%</span>\n" "$(echo "scale=1; ( `echo $sensors | cut -d ' ' -f 3 | tr -d '+°C'` + `echo $sensors | cut -d ' ' -f 12 | tr -d '+°C'` + `echo $sensors | cut -d ' ' -f 21 | tr -d '+°C'` + `echo $sensors | cut -d ' ' -f 30 | tr -d '+°C'` ) / 4" | bc )" "$(top -b -n2 | grep "Cpu(s)"|tail -n 1 | awk '{print $2 + $4}')"
interval=2

[ram]
command=printf "<span foreground=\"#ff0000\">""%sMB/%sGB[%s%%]""</span>" "$(free -m | grep "Mem:" | tr -s ' ' | cut -d ' ' -f 3)" "$(echo "scale=2;$( free -m | grep 'Mem:' | tr -s ' ' | cut -d ' ' -f 2 ) / 1000" | bc)" "$(echo "scale=1; $(free -m | grep "Mem:" | tr -s ' ' | cut -d ' ' -f 3) * 100 / $(free -m | grep 'Mem:' | tr -s ' ' | cut -d ' ' -f 2)" | bc | sed -r 's/^(-?)\./\10\./')"
interval=5

[disk]
command=printf "%s%s" `echo "scale=2;$(df -m | grep "/dev/root" | tr -s ' ' | cut -d ' ' -f 4) / 1000" | bc` "GB"
interval=10

[volume]
command=pactllistsinks=$(pactl list sinks | grep -A 9 "Sink #0" | grep -A 1 "Mute:");volume=$(echo "$pactllistsinks" | grep "Volume:" | tr -s ' ' | cut -d ' ' -f 5 | tr -d '%');mute=$(echo "$pactllistsinks" | grep "Mute:" | tr -s ' ' | cut -d ' ' -f 2); printf "%s [%s%%]" "$( [ "$mute" == "yes" ] && echo "Muted" || echo "$( [ $volume -le 0 ] && echo -n "" || echo -n "$( [ $volume -lt 50 ] && echo -n "" || echo -n "")" )")" "$volume"
interval=5

[date]
command=date "+ %a %Y-%m-%d"
interval=1

[time]
command=date "+ %-I:%M:%S%p"
interval=1
