#!/bin/bash


trap "rm /home/jake/.battery.log" EXIT SIGINT SIGTERM


timeLeft=""

while :
do
	timeLeft=`acpi | cut -d ' ' -f 5`
	hoursLeft=`echo "$timeLeft" | cut -d ':' -f 1 | sed "s/^0*\([1-9]\)/\1/;s/^0*$/0/"`
	minutesLeft=`echo "$timeLeft" | cut -d ':' -f 2 | sed "s/^0*\([1-9]\)/\1/;s/^0*$/0/"`
	totalMinutesLeft=$(( ( $hoursLeft * 60 ) + $minutesLeft ))
	
	echo "$totalMinutesLeft" >> /home/jake/.battery.log
	
	sleep 1
done

