#!/bin/bash

#Script carries out function of decreasing various values

argument="$1"

if [ "$argument" == "brightness" ];then
	currentBrightness=`cat /sys/class/backlight/intel_backlight/brightness`
	if [ $currentBrightness -gt 0 ];then
		currentBrightnessDecrement=$(( $currentBrightness - 1 ))
		sudo bash -c "echo $currentBrightnessDecrement > /sys/class/backlight/intel_backlight/brightness"
	fi
fi

if [ "$argument" == "volume" ];then
	pactl set-sink-volume 0 -1%
fi
