#!/bin/bash

#Script carries out function of increasing various values


argument="$1"

if [ "$argument" == "brightness" ];then
	currentBrightness=`cat /sys/class/backlight/intel_backlight/brightness`
	maxBrightness=`cat /sys/class/backlight/intel_backlight/max_brightness`
	if [ $currentBrightness -lt $maxBrightness ];then
		currentBrightnessIncrement=$(( $currentBrightness + 1 ))
		sudo bash -c "echo $currentBrightnessIncrement > /sys/class/backlight/intel_backlight/brightness"
	fi
fi

if [ "$argument" == "volume" ];then
	pactl set-sink-volume 0 +1%
fi
