#!/bin/sh

sink="alsa_output.pci-0000_00_1f.3-platform-skl_hda_dsp_generic.HiFi__Speaker__sink"

if [ ! -z $BLOCK_BUTTON ]; then
	case $BLOCK_BUTTON in
		1) pactl set-sink-volume "$sink" -1%  ;;
		2) pactl set-sink-mute   "$sink" toggle ;;
		3) pactl set-sink-volume "$sink" +1%  ;;
		5) pactl set-sink-volume "$sink" -5%  ;;
		4) pactl set-sink-volume "$sink" +5%  ;;
	esac
fi

volume=`pactl get-sink-volume "$sink" | head -1 | tr -d ' ' | sed 's/.*front-left:[0-9]\+\/\([0-9]\+\)%.*/\1/'`

mute=`pactl get-sink-mute "$sink" | tr -d ' ' | sed 's/.*:\(.*\)/\1/'`

icon=""

if [ "$mute" == "yes" ]; then
	icon=""
elif [ $volume -eq 0 ]; then
	icon=""
elif [ $volume -gt 0 ] && [ $volume -lt 50 ]; then
	icon=""
elif [ $volume -ge 50 ]; then
	icon=""
fi

echo "${icon} [${volume}%]"
