[[ $- != *i* ]] && return
alias ls='ls --color=auto'
PS1='[\u@\h \W]\$ '

source /home/jake/.git-autocomplete

#USER GLOBAL VARIABLES
export TIME_FORMAT="%-I:%M:%S%p"
export DATE_FORMAT="%a %-d/%-m/%Y"
export PATH=$PATH":/home/jake/Programming/Bash/"

#USER ALIASES
alias cp='sudo cp'
alias mv='sudo mv'
alias rm='sudo rm -R'
alias l='sudo ls --color=auto -Al'
alias me='sudo chmod a+x'
alias find='sudo find / -name'
alias sd='sudo shutdown now'
alias rb='sudo reboot'
alias compile='sudo g++ -o run.exe main.cpp --std=c++14'
alias compileopengl='sudo g++ -o run.exe main.cpp -lglfw -lGL -lm -lXrandr -lXi -lX11 -lXxf86vm -lpthread -lGLEW --std=c++14'
alias run='./run.exe'


alias mergeXresources='sudo xrdb -merge /home/jake/.config/.Xresources'

alias v='sudo vim'
alias vbashrc='v /home/jake/.bashrc; cp /home/jake/.bashrc /root/.bashrc; bash'
alias vxinitrc='v /home/jake/.xinitrc; cp /home/jake/.xinitrc /root/.xinitrc'
alias vi3config='v /home/jake/.config/i3/config; cp /home/jake/.config/i3/config /root/.config/i3/config'
alias vXresources='v /home/jake/.config/.Xresources; cp /home/jake/.config/.Xresources /root/.config/.Xresources; mergeXresources'
alias vpacmanconf='v /etc/pacman.conf'
alias vvimrc='v /home/jake/.vimrc; cp /home/jake/.vimrc /root/.vimrc'
alias vblocks='sudo vim /home/jake/.config/i3blocks/config; cp /home/jake/.config/i3blocks/config /root/.config/i3blocks/config'
alias vmain='sudo vim ./main.cpp'

#Notes aliases
alias cdnotes='cd /home/jake/notes/'
alias cd12='cd /home/jake/notes/12/'
alias cd1='cd /home/jake/notes/12/1_*'
alias cd2='cd /home/jake/notes/12/2_*'
alias cd3='cd /home/jake/notes/12/3_*'
alias cd4='cd /home/jake/notes/12/4_*'
alias cd5='cd /home/jake/notes/12/5_*'
alias cd6='cd /home/jake/notes/12/6_*'

alias nn='sudo vim `date "+%Y-%m-%d.md"`' #Create New note
alias cn='pwd="`pwd`"; cd /home/jake/notes/; git add .; git commit -m "update `date "+%Y-%m-%d"`"; git push; cd "$pwd"' #Commit notes
alias vmaster="sudo vim ./master.md"
alias vtodo='sudo vim /home/jake/notes/todo.md'
alias vkeydates='sudo vim "/home/jake/notes/12/1_AP Literature and Composition/keydates.md"'

