# i3blocks config file

#list of valid attributes
# align
# color
# command
# full_text
# instance
# interval
# label
# min_width
# name
# separator
# separator_block_width
# short_text
# signal
# urgent

# Global properties
command=/usr/lib/i3blocks/$BLOCK_NAME
separator_block_width=15
markup=pango

[battery]
command=/home/jake/Programming/Bash/current battery_formatted
interval=1

[brightness]
command=/home/jake/Programming/Bash/current brightness_formatted
interval=1

[availableupdates]
command=/home/jake/Programming/Bash/current availableupdates_formatted
interval=60

[volume]
command=/home/jake/Programming/Bash/current volume_formatted
interval=1

[wireless]
command=/home/jake/Programming/Bash/current wireless_formatted
interval=1

[date]
command=/home/jake/Programming/Bash/current date
interval=1

[time]
command=/home/jake/Programming/Bash/current time
interval=1


