#!/bin/sh

sensors=`sensors | grep -A 6 "coretemp-isa-0000"`

core_0_temp=`echo "$sensors" | grep "Core 0:" | tr -s " " | cut -d " " -f 3 | tr -d "+°C"`
core_1_temp=`echo "$sensors" | grep "Core 1:" | tr -s " " | cut -d " " -f 3 | tr -d "+°C"`
core_2_temp=`echo "$sensors" | grep "Core 2:" | tr -s " " | cut -d " " -f 3 | tr -d "+°C"`
core_3_temp=`echo "$sensors" | grep "Core 3:" | tr -s " " | cut -d " " -f 3 | tr -d "+°C"`

avg_temp=`echo "scale=1; (${core_0_temp} + ${core_1_temp} + ${core_2_temp} + ${core_3_temp}) / 4" | bc`

echo "<span foreground='#6666ff'>${avg_temp}°C</span>"
