#!/bin/sh

BACKLIGHT_PATH="/sys/class/backlight/intel_backlight"

min=0
max=`cat "${BACKLIGHT_PATH}/max_brightness"`
current=`cat "${BACKLIGHT_PATH}/brightness"`


USAGE() {
	echo "Error: invalid usage."
	echo "USAGE: brightness inc|dec|set [number]"
	exit
}

withinBounds() {
	if [ $1 -ge $min ] && [ $1 -le $max ]; then
		echo "yes"
	else
		echo "no"
	fi
}

increaseBrightness() {
	# If user does not supply an amount to increase by, then it is set to 1
	newBrightness=$(( $current + $1 ))
	if [ `withinBounds $newBrightness` == "yes" ]; then
		sudo /home/jake/programming/shell/backlight_set $newBrightness
	fi
}

decreaseBrightness() {
	# If user does not supply an amount to decrease by, then it is set to 1
	newBrightness=$(( $current - $1 ))
	if [ `withinBounds $newBrightness` == "yes" ]; then
		sudo /home/jake/programming/shell/backlight_set $newBrightness
	fi
}

setBrightness() {
	if [ `withinBounds $1` == "yes" ]; then
		sudo /home/jake/programming/shell/backlight_set $1
	fi
}

if [ $# -eq 1 ]; then
	case $1 in
		"inc") increaseBrightness 1;;
		"dec") decreaseBrightness 1;;
		*) USAGE;;
	esac
elif [ $# -eq 2 ]; then
	case $1 in
		"inc") increaseBrightness $2;;
		"dec") decreaseBrightness $2;;
		"set") setBrightness $2;;
		*) USAGE;;
	esac
else
	USAGE
fi
