# /etc/i3blocks.conf


# List of valid properties:
# align
# color
# command
# full_text
# instance
# interval
# label
# min_width
# name
# separator
# separator_block_width
# short_text
# signal
# urgent

# Global properties
command=/usr/libexec/i3blocks/$BLOCK_NAME
separator_block_width=15
markup=none

[brightness]
command=/home/jake/programming/shell/brightness format
interval=10

[battery]
command=/home/jake/programming/shell/battery
interval=10
markup=pango

[date]
command=date "+ ${DATE_FORMAT}"
interval=5

[time]
command=date "+ ${TIME_FORMAT}"
interval=1
