command=$SCRIPT_DIR/$BLOCK_NAME
separator_block_width=15
markup=pango

[gpu]
command=exec /home/jake/Programming/Bash/gpucurrent
interval=1

[cpu]
command=exec /home/jake/Programming/Bash/cpu
interval=1

[ram]
command=exec /home/jake/Programming/Bash/ramcurrent
interval=1

[diskspace]
command=exec /home/jake/Programming/Bash/diskspace
interval=10

[pacmanupdates]
command=exec /home/jake/Programming/Bash/availableupdates
interval=30

[volume]
command=exec /home/jake/Programming/Bash/volumecurrent
interval=1

[date]
command=exec /home/jake/Programming/Bash/datecurrent
interval=1

[time]
command=exec /home/jake/Programming/Bash/timecurrent
interval=1
